name: CI
on:
  pull_request:
    paths:
      - .github/workflows/ci.yml
      - Package.*
      - Sources/**/*.swift
      - Tests/**/*.swift
      - .github/matrix.json
concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  xcode-versions:
    name: Extract latest Xcode version from matrix
    runs-on: ubuntu-latest
    outputs:
      xcode-versions: ${{ steps.extract-xcode-version.outputs.xcode-versions }}
      latest: ${{ steps.extract-xcode-version.outputs.latest-xcode-version }}
    steps:
      - uses: actions/checkout@v3
      - id: extract-xcode-version
        run: |
          echo "xcode-versions=$(cat .github/matrix.json | jq -rc '.xcode_version')" >> $GITHUB_OUTPUT
          echo "latest-xcode-version=$(cat .github/matrix.json | jq -r '.xcode_version | max')" >> $GITHUB_OUTPUT
  test:
    name: Test
    needs: xcode-versions
    runs-on: macos-12
    concurrency: 
      group: ${{ github.head_ref }}-${{ github.workflow }}-${{ matrix.xcode }}-${{ matrix.destination }}
      cancel-in-progress: true
    strategy:
      matrix:
        xcode: ${{ fromJson(needs.xcode-versions.outputs.xcode-versions) }}
      fail-fast: false
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            .build/SourcePackages/checkouts
          key: ${{ runner.os }}-xcode-${{ matrix.xcode }}-${{ hashFiles('Package.swift') }}
          restore-keys: |
            ${{ runner.os }}-xcode-${{ matrix.xcode }}-
      - name: test
        run: |
          defaults write com.apple.dt.XCBuild EnableSwiftBuildSystemIntegration 1
          set -o pipefail && \
          xcrun xcodebuild \
          -enableCodeCoverage YES \
          -scheme XcodeArch \
          -destination "platform=macOS" \
          -derivedDataPath '.build' \
          -resultBundlePath 'test_output/TestResult.xcresult' \
          clean test | xcpretty
      - name: Upload test result
        uses: actions/upload-artifact@v3
        if: ${{ matrix.xcode }} == ${{ needs.xcode-versions.outputs.latest }} && (success() || failure())
        with:
          name: TestResult
          path: test_output
          if-no-files-found: error
          retention-days: 1
  xcodebuild_result:
    name: Export xcodebuild test result
    needs: test
    runs-on: macOS-12
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: test_output
      - uses: kishikawakatsumi/xcresulttool@v1
        if: success() || failure()
        with:
          path: test_output/TestResult/TestResult.xcresult
          show-passed-tests: false
          show-code-coverage: false
          upload-bundles: true
